export const msg = {
  AUTH_REG_OK: 'Registration successful',
  AUTH_REG_FAIL: 'Registration failed:',
  AUTH_LOGIN_OK: 'Login successful',
  AUTH_LOGIN_FAIL: 'Login failed:',
  AUTH_CRED_INVALID: 'Invalid credentials',
  AUTH_EMAIL_INVALID: 'Invalid email format',
  AUTH_PASS_SHORT: 'Password must be at least 8 characters',
  AUTH_PASS_LONG: 'Password must be at most 32 characters',
  AUTH_FIELDS_REQ: 'Email and password are required',
  AUTH_USER_EXISTS: 'User already exists',

  PARAM_USER_ID: 'user_id query param is required',
  PARAM_BIKE_ID: 'bike_id query param is required',
  PARAM_ADD_BIKE: 'user_id, make, model, year, and odo are required',
  PARAM_UPDATE_BIKE: 'id, user_id, make, model, year, and odo are required',
  PARAM_DELETE_BIKE: 'bike_id and user_id are required',
  PARAM_BIKE_NAME: 'bike_id and name are required',
  PARAM_MAINT_LOG: 'bike_id, name, date, and odo are required',
  PARAM_INT_KM: 'interval_km is required',
  PARAM_INT_DAYS: 'interval_days are required',
  PARAM_INT_KM_POS: 'interval_km must be a positive integer',
  PARAM_INT_DAYS_POS: 'interval_days must be a positive integer',
  PARAM_ODO_NON_NEG: 'odo must be a positive integer',

  BIKE_EXISTS: 'Bike already exists',
  BIKE_NOT_FOUND: 'Bike not found',
  BIKE_CREATE_OK: 'Bike created successfully',
  BIKE_CREATE_FAIL: 'Create bike failed:',
  BIKE_UPDATE_OK: 'Bike updated successfully',
  BIKE_UPDATE_FAIL: 'Update bike failed:',
  BIKE_DELETE_OK: 'Bike deleted successfully',
  BIKE_DELETE_FAIL: 'Delete bike failed:',
  BIKE_LIST_FAIL: 'List bikes failed:',
  BIKE_YEAR_RANGE: 'Year must be an integer between 1900 and 2100',
  BIKE_YEAR_INVALID: 'Invalid year',
  BIKE_ODO_DECR: 'Odometer cannot decrease',

  MAINT_LOG_FIELDS: 'At least one maintenance log field must be provided',
  MAINT_DATE_INVALID: 'Invalid date',
  MAINT_CREATE_OK: 'Maintenance created successfully',
  MAINT_LOG_CREATE_OK: 'Maintenance log created successfully',
  MAINT_LOG_CREATE_FAIL: 'Create maintenance log failed:',
  MAINT_UPDATE_OK: 'Maintenance updated successfully',
  MAINT_SCHED_OK: 'Maintenance scheduled successfully',
  MAINT_UPDATE_FAIL: 'Update maintenance failed:',
  MAINT_LIST_FAIL: 'List maintenance failed:',
  MAINT_LOG_LIST_FAIL: 'List maintenance logs failed:',

  SYS_ERR_INTERNAL: 'Internal server error',
  SYS_START_FAIL: 'Failed to start server:',
  SYS_DB_URL_REQ: 'DATABASE_URL is required',
  SYS_API_RUNNING: 'MotoCare Maintenance Tracker API is running',
};
